### ISSUE TITLE
TypeError: "this.args is not iterable" in command "userinfo"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#126]
<h3>Reported by Vinnis Erbschaft#7032 (877926065010536448) with bot 948978571802710047</h3>

TypeError: this.args is not iterable
    at /home/container/Commands/Information/userinfo.js:22:160
    at Array.some (<anonymous>)
    at /home/container/Commands/Information/userinfo.js:22:141
    at Collection.find (/home/container/node_modules/@discordjs/collection/dist/collection.cjs:104:11)
    at ChatInputCommandInteraction.run (/home/container/Commands/Information/userinfo.js:22:78)
    at ChatInputCommandInteraction.interactionCreate (/home/container/Events/interactionCreate.js:58:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Mephisto5558** [comment]
fixed in c91a2807aa8a5672bd83c6b819253cf95944aa47
