### ISSUE TITLE
DiscordAPIError[50035]: "Invalid Form Body
limit[NUMBER_TYPE_MIN]: int value should be greater than or equal to 1." in command "purge"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#132]
<h3>Reported by .̔̏𝗠𝗲𝗽𝗵𝗶𝘀𝘁𝗼#5558 (691550551825055775) with bot 948978571802710047</h3>

DiscordAPIError[50035]: Invalid Form Body
limit[NUMBER_TYPE_MIN]: int value should be greater than or equal to 1.
    at SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:743:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:549:14)
    at async REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:988:22)
    at async MessageManager._fetchMany (/home/container/node_modules/discord.js/src/managers/MessageManager.js:106:18)
    at async TextChannel.bulkDelete (/home/container/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:326:20)
    at async Message.run (/home/container/Commands/Moderation/purge.js:27:7)
    at async Message.messageCreate (/home/container/Events/messageCreate.js:82:9)

**Comment by Mephisto5558** [comment]
fixed with e74b49d5303319ba7fc54b583743d3d49af13156
