### ISSUE TITLE
Error: "getaddrinfo ENOTFOUND 5038-smile-ooooo" in command "addemoji"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#141]
<h3>Reported by Heldenstayn#0460 (852965004729909258) with bot 948978571802710047</h3>

Error: getaddrinfo ENOTFOUND 5038-smile-ooooo
    at AxiosError.from (/home/container/node_modules/axios/dist/node/axios.cjs:725:14)
    at RedirectableRequest.handleRequestError (/home/container/node_modules/axios/dist/node/axios.cjs:2465:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/home/container/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Mephisto5558** [comment]
fixed with [f9dc37c](https://github.com/Mephisto5558/Teufelsbot/commit/f9dc37c73ab6ce55e5acb489a27f6916a50a8174)
