### ISSUE TITLE
FetchError: "invalid json response body at https://nekobot.xyz/api/imagegen?type=magik&image=https://cdn.discordapp.com/avatars/852965004729909258/a_6df290f6b66a9bb94cae077c69d053d9.gif?size=2048&intensity=10& reason: Unexpected token < in JSON at position 0" in command "image"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#151]
<h3>Reported by Heldenstayn#0460 (852965004729909258) with bot 948978571802710047</h3>

FetchError: invalid json response body at https://nekobot.xyz/api/imagegen?type=magik&image=https://cdn.discordapp.com/avatars/852965004729909258/a_6df290f6b66a9bb94cae077c69d053d9.gif?size=2048&intensity=10& reason: Unexpected token < in JSON at position 0
    at /home/container/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Message.run (/home/container/Commands/Fun/image.js:64:18)

**Comment by Mephisto5558** [comment]
need to add try catch there
