### ISSUE TITLE
TypeError: "Cannot read properties of undefined (reading '0')" in command "serverinfo"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#193]
<h3>Reported by .̔̏𝗠𝗲𝗽𝗵𝗶𝘀𝘁𝗼#5558 (691550551825055775) with bot 948978571802710047</h3>

TypeError: Cannot read properties of undefined (reading '0')
    at ChatInputCommandInteraction.run (/home/container/Commands/Information/serverinfo.js:19:92)
    at ChatInputCommandInteraction.interactionCreate (/home/container/Events/interactionCreate.js:79:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Mephisto5558** [comment]
fixed with [eb36991](https://github.com/Mephisto5558/Teufelsbot/commit/eb369915fe6bfa4fcc7821306f56ea500d55ab34)
