### ISSUE TITLE
TypeError: "Cannot read properties of null (reading 'toString')" in command "birthday"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#217]
<h3>Reported by Faico10032#7187 (858386282485252107) with bot 948978571802710047</h3>

TypeError: Cannot read properties of null (reading 'toString')
    at ChatInputCommandInteraction.run (/home/container/Commands/Fun/birthday.js:57:41)
    at ChatInputCommandInteraction.interactionCreate (/home/container/Events/interactionCreate.js:86:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Mephisto5558** [comment]
Fixed in 1bb3ef9
