### ISSUE TITLE
DiscordAPIError[50006]: "Cannot send an empty message" in command "ban"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#232]
<h3>Reported by .̔̏𝗠𝗲𝗽𝗵𝗶𝘀𝘁𝗼#5558 (691550551825055775) with bot 948978571802710047</h3>

DiscordAPIError[50006]: Cannot send an empty message
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async InteractionWebhook.editMessage (/home/container/node_modules/discord.js/src/structures/Webhook.js:338:15)
    at async ChatInputCommandInteraction.editReply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:158:17)

**Comment by Mephisto5558** [comment]
Cannot reproduce
