### ISSUE TITLE
TypeError: "this.options.embeds?.map is not a function" in command "kick"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#277]
<h3>Reported by mephisto5558 (691550551825055775) with bot 948978571802710047</h3>

TypeError: this.options.embeds?.map is not a function
    at MessagePayload.resolveBody (/home/container/node_modules/discord.js/src/structures/MessagePayload.js:200:36)
    at InteractionWebhook.editMessage (/home/container/node_modules/discord.js/src/structures/Webhook.js:336:50)
    at ChatInputCommandInteraction.editReply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:158:36)
    at ChatInputCommandInteraction.bankick (/home/container/Utils/bankick.js:30:19)
    at ChatInputCommandInteraction.interactionCreate (/home/container/Events/interactionCreate.js:67:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Mephisto5558** [comment]
fixed with 731991a54c3aceae1732ab739d44cd9d18f5cb29
