### ISSUE TITLE
DiscordAPIError[50035]: "Invalid Form Body
content[BASE_TYPE_MAX_LENGTH]: Must be 2000 or fewer in length." in command "wiki"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#280]
<h3>Reported by floarmy (922468148417028147) with bot 948978571802710047</h3>

DiscordAPIError[50035]: Invalid Form Body
content[BASE_TYPE_MAX_LENGTH]: Must be 2000 or fewer in length.
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:687:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1072:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:913:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1218:22)
    at async TextChannel.send (/home/container/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:162:15)
    at async Message.customReply (/home/container/Utils/prototypeRegisterer/message_customReply.js:23:19)

**Comment by Mephisto5558** [comment]
possibly fixed in b25597e
