### ISSUE TITLE
TypeError: "The argument 'file' cannot be empty. Received ''" in command "exec"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#333]
<h3>Reported by mephisto5558 (691550551825055775) with bot 948978571802710047</h3>

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
    at normalizeSpawnArguments (node:child_process:552:11)
    at spawn (node:child_process:754:13)
    at Object.execFile (node:child_process:351:17)
    at exec (node:child_process:234:25)
    at node:child_process:243:21
    at Message.run ([cwd]/Commands/Owner-Only/exec.js:13:60)
    at Message.commandExecutionWrapper ([cwd]/Utils/commandExecutionWrapper.js:10:23)
    at Message.messageCreate ([cwd]/Events/messageCreate.js:28:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Mephisto5558** [comment]
I knew I forgot something
