### ISSUE TITLE
DiscordAPIError[50035]: "Invalid Form Body
content[BASE_TYPE_MAX_LENGTH]: Must be 2000 or fewer in length." in command "exec"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#349]
<h3>Reported by mephisto5558 (691550551825055775) with bot 948978571802710047</h3>

DiscordAPIError[50035]: Invalid Form Body
content[BASE_TYPE_MAX_LENGTH]: Must be 2000 or fewer in length.
    at handleErrors ([cwd]/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest ([cwd]/node_modules/@discordjs/rest/dist/index.js:1120:23)
    at async SequentialHandler.queueRequest ([cwd]/node_modules/@discordjs/rest/dist/index.js:953:14)
    at async _REST.request ([cwd]/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async TextChannel.send ([cwd]/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:155:15)
    at async Message.customReply ([cwd]/Utils/prototypeRegisterer/message_customReply.js:41:13)
    at async Message.commandExecutionWrapper ([cwd]/Utils/commandExecutionWrapper.js:17:5)

**Comment by Mephisto5558** [comment]
**Todo**: on customReply, if message is to long, send it as attachment
