### ISSUE TITLE
TypeError: "Cannot read properties of null (reading 'shardId')" in command "info"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#410]
<h3>Reported by mephisto5558 (691550551825055775) with bot 948978571802710047</h3>

TypeError: Cannot read properties of null (reading 'shardId')
    at Message.run ([cwd]/Commands/Information/info.js:17:45)
    at Message.commandExecutionWrapper ([cwd]/Utils/commandExecutionWrapper.js:28:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Mephisto5558** [comment]
\+
An error occurred while trying to send your error report.
```
dev.send is not a function
```
Please message the dev directly.

**Comment by Mephisto5558** [comment]
Note: cmd executed in DMs, should be added to the error report
