### ISSUE TITLE
TypeError [CommandInteractionOptionNoSubcommand]: "No subcommand specified for interaction." in command "afk"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#419]
<h3>Reported by mephisto5558 (691550551825055775) with bot 948978571802710047</h3>

TypeError [CommandInteractionOptionNoSubcommand]: No subcommand specified for interaction.
    at CommandInteractionOptionResolver.getSubcommand ([cwd]/node_modules/discord.js/src/structures/CommandInteractionOptionResolver.js:113:13)
    at ChatInputCommandInteraction.run ([cwd]/Commands/Useful/afk.js:30:23)
    at ChatInputCommandInteraction.commandExecutionWrapper ([cwd]/Utils/commandExecutionWrapper.js:28:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Mephisto5558** [comment]
Probably a bug in the slash command registerer, no subcommands or aliases are registered?

**Comment by Mephisto5558** [comment]
I have reasonable belief that this has been fixed in 80dcf7f.
Will reopen if the issue persists.
