### ISSUE TITLE
MongoServerSelectionError: "connection timed out" in command "ping"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#420]
<h3>Reported by mephisto5558 (691550551825055775) with bot 948978571802710047</h3>

MongoServerSelectionError: connection timed out
    at EventTarget.<anonymous> ([cwd]/node_modules/mongodb/lib/sdam/topology.js:276:34)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at EventTarget.dispatchEvent (node:internal/event_target:755:26)
    at abortSignal (node:internal/abort_controller:370:10)
    at TimeoutController.abort (node:internal/abort_controller:392:5)
    at Timeout.<anonymous> ([cwd]/node_modules/mongodb/lib/utils.js:1011:92)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)

**Comment by Mephisto5558** [comment]
Hm, not a usual issue, will add something to prevent it leaking to users, as this was probably coming from trying to update the command usage stats DB entry.

**Comment by Mephisto5558** [comment]
I decided that this behavior will continue, so I'll be notified about network issues.
