### ISSUE TITLE
DiscordAPIError[10062]: "Unknown interaction" in command "undefined"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#452]
<h3>Reported by mephisto5558 (691550551825055775) with bot 948978571802710047</h3>

DiscordAPIError[10062]: Unknown interaction
    at handleErrors ([cwd]/node_modules/@discordjs/rest/dist/index.js:727:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest ([cwd]/node_modules/@discordjs/rest/dist/index.js:831:23)
    at async _REST.request ([cwd]/node_modules/@discordjs/rest/dist/index.js:1272:22)
    at async ButtonInteraction.update ([cwd]/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:237:5)
    at async ButtonInteraction.messageComponentHandler ([cwd]/Utils/componentHandler.js:29:39)
    at async Client.<anonymous> ([cwd]/Handlers/slash_command_handler.js:91:11)

**Comment by Mephisto5558** [comment]
button click spam on clickcounter
