### ISSUE TITLE
RangeError: "Non-premium buttons must have a label and/or an emoji." in command "button"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#462]
<h3>Reported by mephisto5558 (691550551825055775) with bot 948978571802710047</h3>

RangeError: Non-premium buttons must have a label and/or an emoji.
    at validateRequiredButtonParameters ([cwd]/node_modules/@discordjs/builders/dist/index.js:563:13)
    at ButtonBuilder.toJSON ([cwd]/node_modules/@discordjs/builders/dist/index.js:711:5)
    at [cwd]/node_modules/@discordjs/builders/dist/index.js:1479:64
    at Array.map (<anonymous>)
    at ActionRowBuilder.toJSON ([cwd]/node_modules/@discordjs/builders/dist/index.js:1479:35)
    at [cwd]/node_modules/discord.js/src/structures/MessagePayload.js:151:82
    at Array.map (<anonymous>)
    at MessagePayload.resolveBody ([cwd]/node_modules/discord.js/src/structures/MessagePayload.js:150:49)
    at TextChannel.send ([cwd]/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:178:61)
    at ChatInputCommandInteraction.run ([cwd]/Commands/Useful/button.js:91:65)
    at ChatInputCommandInteraction.commandExecutionWrapper ([cwd]/Utils/commandExecutionWrapper.js:27:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> ([cwd]/Handlers/slash_command_handler.js:91:11)

**Comment by Mephisto5558** [comment]
this should not be thrown, but shown to the user instead
