### ISSUE TITLE
TypeError: "Cannot read properties of undefined (reading 'start')" in command "giveaway"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#87]
<h3>Reported by .̔̏𝗠𝗲𝗽𝗵𝗶𝘀𝘁𝗼#5558 (691550551825055775) with bot 948978571802710047</h3>

TypeError: Cannot read properties of undefined (reading 'start')
    at Command.run (/home/runner/Teufelsbot/Commands/Fun/giveaway.js:260:45)
    at module.exports (/home/runner/Teufelsbot/Events/interactionCreate.js:37:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Mephisto5558** [comment]
fixed in [fcf287a](https://github.com/Mephisto5558/Teufelsbot/commit/fcf287a48ea50f667bd479de5e7d7081ecfff0fc)
