### ISSUE TITLE
TypeError: "message.edit is not a function" in command "info"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#88]
<h3>Reported by .̔̏𝗠𝗲𝗽𝗵𝗶𝘀𝘁𝗼#5558 (691550551825055775) with bot 948978571802710047</h3>

TypeError: message.edit is not a function
    at Command.run (/home/runner/Teufelsbot/Commands/Information/info.js:38:97)
    at module.exports (/home/runner/Teufelsbot/Events/interactionCreate.js:37:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Mephisto5558** [comment]
fixed with commit 7ff05d8
