### ISSUE TITLE
TypeError: "amount.limit is not a function" in command "give"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#98]
<h3>Reported by Vync#0206 (448801471589384203) with bot 948978571802710047</h3>

TypeError: amount.limit is not a function
    at Command.run (/home/container/Commands/Economy/give.js:60:21)
    at module.exports (/home/container/Events/interactionCreate.js:40:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Mephisto5558** [comment]
fixed with [39aab2e](https://github.com/Mephisto5558/Teufelsbot/commit/39aab2e5414db1e45033c299a16e4cef958e5a55)
