### ISSUE TITLE
TypeError: "Cannot read properties of undefined (reading 'users')" in command "mgstats"

### ISSUE THREAD

**Issue by Mephisto5558** [Mephisto5558/Teufelsbot#99]
<h3>Reported by .̔̏𝗠𝗲𝗽𝗵𝗶𝘀𝘁𝗼#5558 (691550551825055775) with bot 948978571802710047</h3>

TypeError: Cannot read properties of undefined (reading 'users')
    at Object.run (/home/container/Commands/Minigames/mgStats.js:134:70)
    at module.exports (/home/container/Events/interactionCreate.js:40:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Mephisto5558** [comment]
fixed in commit a91de2cab66923bff89256dbd725f9c88b658718
